config/routes.rb
Textlog::Application.routes.draw do
  root 'welcome#homepage'

  get '/debug' => 'debug#index'

  resources :messages
  resources :rules, except: [:show] do
    member do
      put 'bump'
    end
  end
  resources :activities, only: [:create, :index]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/message.rb
class Message < ActiveRecord::Base
  has_one :activity
  # When activities table is empty, 'Activity.pluck(:message_id)' returns '[]'.
  # When that happens, the where clause because "where('id not in (?)', [])",
  # which returns nothing. By defaulting '[]' to '[0]', we avoid this problem
  # since db ids are never 0.
  scope :unparsed, -> { where('id not in (?)', Activity.pluck(:message_id) + [0])
                       .order('created_at DESC') }
  validates :message, presence: true

  #
  # Commands that can be called on message models
  #
  COMMANDS = ['match']

  def match(pattern)
    # This line raises an error when 'pattern' is not valid regex. When that
    # happens, rescue nil and act as if there was no match.
    self.message.match(/#{pattern}/i) if pattern rescue nil
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :must_be_logged_in, only: [:create, :destroy, :update]
  skip_before_filter :verify_authenticity_token, only: :create # For Twillio

  def create
    # When request comes from Twillio
    if params['Body'].present?
      Message.create(message: params['Body'])
      render nothing: true
    # When request comes locally
    else
      @message = Message.new(message_params)
      if @message.save
        redirect_to :messages, notice: 'Message was successfully created.'
      else
        render :new
      end
    end
  end

  def destroy
    Message.find(params[:id]).destroy
    redirect_to :messages, alert: 'Message was successfully deleted.'
  end

  def edit
    @message = Message.find(params[:id])
  end

  def index
    @messages = Message.unparsed
  end

  def new
    @message = Message.new
  end

  def show
    @message = Message.find(params[:id])
    @activity, @matchers_executed, @other_applicable_matchers = RulesEngine.new(@message).execute

    # Validate activity such that if there is any validation error, we can show
    # them now and have user correct them by editing rules.
    @activity.valid?

    # When a user clicks off to edit or add a rule, instruct rules controller
    # to return user back to this page.
    @redirect_path = message_path(@message)
  end

  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(message_params)
      redirect_to :messages, notice: 'Message was successfully updated.'
    else
      render :edit
    end
  end

  private

    def message_params
      params.require(:message).permit(:message)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for message do |f| %>
  <div class='row-fluid'>
    <%= f.text_area :message, class: 'span6', placeholder: 'Message' %>
  </div>

  <%= render 'shared/form_errors', model: message %>

  <div class='row-fluid'>
    <%= f.submit class: 'btn btn-primary span6' %>
  </div>

  <div class='row-fluid'>
    <%= link_to 'Cancel', :messages, class: 'cancel' %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<p class='well well-small'><%= message.message %></p>

app/views/messages/_message_well.html.erb
<p class='well well-small'><%= message.message %></p>

app/views/messages/_structured_data.html.erb
<dl class='dl-horizontal structured-data'>
  <dt>Activity:</dt>
  <dd>
    <%= dash_if_blank(activity.activity) %>
    <% if activity.activity_is_new? %><sup>new</sup><% end %>
  </dd>

  <dt>Friends:</dt>
  <dd>
    <% if activity.friends.blank? %>
      <%= dash_if_blank(@friends) %>
    <% else %>
      <% activity.friends.sort_by(&:name).each_with_index do |friend, i| %>
        <span class='picture-plus-name'>
          <%= image_tag profile_pic(friend.fb_id), alt: friend.name %>
          <%= friend.name %>
          <% if friend.new_record? %><sup>new</sup><% end %>
          <% unless i == activity.friends.length - 1 %>,<% end %>
        </span>
      <% end %>
    <% end %>
  </dd>

  <dt>Duration:</dt>
  <dd><%= dash_if_blank(duration_formatter(activity.duration)) %></dd>

  <dt>Distance:</dt>
  <dd><%= dash_if_blank(distance_formatter(activity.distance)) %></dd>

  <dt>Reps:</dt>
  <dd><%= dash_if_blank(activity.reps) %></dd>

  <dt>Note:</dt>
  <dd><%= dash_if_blank(activity.note) %></dd>
</dl>

app/views/messages/edit.html.erb
<%= render 'form', message: @message %>

app/views/messages/index.html.erb
<% if @messages.present? %>
  <ol>
    <% @messages.each do |message| %>
      <li>
        <p><%= message.message %></p>
        <div class='glyphicon-plus-action'>
          <a class='parse' href='<%= message_path(message.id) %>'>
            <i class="icon-eye-open"></i>parse</a>
          <a class='edit' href='<%= edit_message_path(message.id) %>'>
            <i class="icon-edit"></i>edit</a>
          <a class='delete' href='<%= message_path(message.id) %>'
             data-method='delete' data-confirm='Are you sure?' rel='nofollow'>
             <i class="icon-trash"></i>delete</a>
        </div>
      </li>
    <% end %>
  </ol>
<% else %>
  <h4>No new message!</h4>
<% end %>

<%= link_to 'Add new', :new_message, class: 'btn page-bottom' %>

app/views/messages/new.html.erb
<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<div class='row-fluid'>
  <div class='message-container span6'>
    <div class='docs docs-activity'>
      <header><h4>Parse preview</h4></header>
      <%= render 'messages/message_well', message: @message %>
      <%= render 'structured_data', activity: @activity %>
    </div>

    <%= form_for @activity do |f| %>
      <input type='hidden' name='message_id' value='<%= @message.id %>' />
      <%= render 'shared/form_errors', model: @activity %>
      <%= f.hidden_field nil, value: @message.id %>
      <%= f.submit 'Parse Message', class: 'btn btn-primary btn-block',
                                    disabled: !@activity.errors.empty? %>
      <%= link_to 'Cancel', :messages, class: 'cancel' %>
    <% end %>
  </div>

  <div class='rules-container span6 well hidden-phone'>
    <h4>Applicable rules</h4>
    <%= render partial: 'rules/rule_docs',
               collection: @matchers_executed,
               as: :matcher %>
    <% if @other_applicable_matchers.present? %>
      <h4>Other applicable rules</h4>
      <%= render partial: 'rules/rule_docs',
                 locals: { show_bump: true },
                 collection: @other_applicable_matchers,
                 as: :matcher %>
    <% end %>
    <%= link_to 'Add new', new_rule_path(message_id: @message.id,
                                         redirect_path: @redirect_path),
                           class: 'btn' %>
  </div>
</div>