config/routes.rb
Textlog::Application.routes.draw do
  root 'welcome#homepage'

  get '/debug' => 'debug#index'

  resources :messages
  resources :rules, except: [:show] do
    member do
      put 'bump'
    end
  end
  resources :activities, only: [:create, :index]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

end

app/models/rule.rb
# A rule can be a matcher or a setter.
# A matcher matches a regex pattern on a message.
# A setter calls a custome setter on an activity.
# A matcher can have many setters, and a setter can belong to a matcher.
# The tell between a matcher and a setter is whether it has matcher_id.
class Rule < ActiveRecord::Base
  before_save :set_cnt_was_last_updated
  belongs_to :matcher, class_name: 'Rule'
  has_many :setters, class_name: 'Rule', foreign_key: 'matcher_id'
  scope :matchers, -> { where(matcher_id: nil)
                       .includes(:setters)
                       .order('rules.updated_at DESC') }
  scope :matchers_for,
    lambda { |command| matchers
                      .where('setters_rules.command = ?', command)
                      .references(:setters) }
  serialize :arg
  validates :arg, presence: true, if: :is_matcher?
  validates :command, inclusion: { in: Message::COMMANDS }, if: :is_matcher?
  validates :command, inclusion: { in: Activity::COMMANDS }, if: :is_setter?

  #
  # Rspec helpers
  #
  def as_json(options = {})
    super(except: [:created_at, :updated_at, :id, :matcher_id],
          include: [matcher: { except: [:created_at, :updated_at, :id] }])
  end

  private

    #
    # Before filters
    #
    def set_cnt_was_last_updated
      self.cnt_was_last_updated = self.cnt_changed?
      return # Rails is not happy when a before filter returns false
    end

    def is_matcher?
      self.matcher_id.nil?
    end

    def is_setter?
      self.matcher_id.present?
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_filter :set_redirect_path, only: [:bump, :create, :destroy, :edit,
                                              :new, :update]
  before_filter :must_be_logged_in, only: [:bump, :create, :destroy, :update]

  def bump
    Rule.find(params[:id]).touch
    redirect_to @redirect_path, notice: 'Rule was successfully bumped up.'
  end

  def create
    @rule = matcher = Rule.new(matcher_params)
    if matcher.valid? && setters_valid?
      matcher.save
      setters_create
      redirect_to @redirect_path, notice: 'Rule was successfully created.'
    else
      render :new
    end
  end

  def destroy
    Rule.find(params[:id]).destroy
    redirect_to @redirect_path, alert: 'Rule was successfully deleted.'
  end

  def edit
    @rule = Rule.matchers.find(params[:id])
  end

  def index
    # Sidebar
    @command_counts = Activity::COMMANDS.map do |command|
                        Rule.matchers_for(command).count
                      end

    # Main
    @rules = if params[:command].present?
               Rule.matchers_for(params[:command])
             else
               Rule.matchers
             end
    if params['sort-by'] == 'most-frequently-used'
      @rules = @rules.order('rules.cnt DESC')
    end

    # When a user clicks off to edit a rule, instruct edit form to preserve
    # filter/sort params when redirecting user back.
    @redirect_path = rules_path(command: params[:command],
                                'sort-by' => params['sort-by'])
  end

  def new
    @rule = Rule.new
    @message = Message.find(params[:message_id]) if params[:message_id]
  end

  def update
    @rule = matcher = Rule.find(params[:id])
    matcher.arg = params[:rule][:arg]
    if matcher.valid? && setters_valid?
      matcher.save
      matcher.setters.destroy_all
      setters_create
      redirect_to @redirect_path, notice: 'Rule was successfully updated.'
    else
      render :edit
    end
  end

  private

    #
    # Before filters
    #
    def set_redirect_path
      @redirect_path = params[:redirect_path] || :rules
    end

    #
    # Helpers
    #
    def setters_valid?
      if params[:commands].nil? || params[:commands].join.blank?
        @rule.errors.add(:setter, "can't be blank") and return
      end

      params[:commands].zip(params[:args]).each do |command, arg|
        if command.present? && arg.blank?
          unless params[:rule][:arg].index("(?<#{command.split('_').last}>")
            @rule.errors.add(command, "can't be blank unless captured") and return
          end
        end
      end

      true
    end

    def setters_create
      if params[:commands].present?
        params[:commands].zip(params[:args]).map do |command, arg|
          Rule.create(command: command, arg: arg, matcher_id: @rule.id)
        end
      end
    end

    #
    # Strong parameters
    #
    def matcher_params
      params.require(:rule).permit(:command, :arg)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
  #
  # Heading helpers
  #
  def rule_heading(matcher)
    verb = if matcher.created_at == matcher.updated_at
             'Created'
           elsif matcher.cnt_was_last_updated?
             'Used'
           else
             'Modified'
           end
    if params['sort-by'] == 'most-frequently-used'
      "#{matcher.cnt}x | #{verb} #{time_ago(matcher.updated_at)} ago"
    else
      "#{verb} #{time_ago(matcher.updated_at)} ago | #{matcher.cnt}x"
    end
  end

  #
  # Select helpers
  #
  def sort_by_options
    [['Most recently used', nil],
     ['Most frequently used', 'most-frequently-used']]
  end

  #
  # Link helpers
  #
  def setter_name(command, i)
    "#{h(command)} <sup>(#{h(@command_counts[i])})</sup>".html_safe
  end

  def setter_href(command)
    rules_path(command: command, 'sort-by' => params['sort-by'])
  end

  #
  # Attribute helpers
  #
  NAMED_CAPTURE = /\?&lt;([a-z]+)&gt;/
  def matcher_arg(arg)
    h(arg).gsub(NAMED_CAPTURE, '?&lt;<em>\1</em>&gt;').html_safe
  end

  def setter_arg(arg, matcher_arg)
    if arg.blank?
      key_values = h(matcher_arg).scan(NAMED_CAPTURE).flatten
                                 .map { |name| "#{name}: <<em>#{name}</em>>" }
                                 .join(', ')
      "{ #{key_values} }".html_safe
    else
      h(arg)
    end
  end

  def current_setters(rule)
    if params[:commands].present?
      setters = params[:commands].zip(params[:args]).map do |command, arg|
        Rule.new(command: command, arg: arg)
      end
    end
    setters ||= rule.new_record? ? [Rule.new] : rule.setters
  end
end

app/views/rules/_fieldset.html.erb
<fieldset>
  <div class='row-fluid select-row'>
    <%= select_tag 'commands[]',
                   options_for_select(Activity::COMMANDS, setter.command),
                   prompt: 'set ...',
                   id: nil, # This partial is rendered multiple times on the page
                   class: 'offset1 input-medium' %>
    <div class='glyphicon-plus-action'>
      <a class='delete' href='#' tabindex='99'>
        <i class='icon-trash'></i>delete
      </a>
    </div>
  </div>

  <div class='row-fluid'>
    <%= text_field_tag 'args[]',
                       '',
                       id: nil, # This partial is rendered multiple times on the page
                       class: 'span11 offset1',
                       value: setter.arg,
                       placeholder: SETTER_PLACEHOLDERS[setter.command] %>
  </div>
</fieldset>

app/views/rules/_form.html.erb
<!-- Message to write rule against if it exists -->
<% if @message %>
  <div class='row-fluid'>
    <div class='span6'>
      <%= render 'messages/message_well', message: @message %>
    </div>
  </div>
<% end %>

<div class='row-fluid'>
  <%= form_for rule, html: { id: 'rule',
                             class: 'docs docs-small span6' } do |f| %>
    <!-- Hidden redirect_path -->
    <% if params[:redirect_path].present? %>
      <input type='hidden'
             name='redirect_path'
             value='<%= params[:redirect_path] %>' />
    <% end %>

    <!-- Matcher -->
    <div class='row-fluid'>
      <%= f.select :command,
                   Message::COMMANDS,
                   {},
                   { class: 'input-medium' } %>
      <div class='glyphicon-plus-action pull-right'>
        <a class='clickoff muted' href='http://rubular.com/' target='_blank'>
          <i class='icon-share-alt'></i>regex help</a>
      </div>
    </div>
    <div class='row-fluid'>
      <%= f.text_field :arg, class: 'span12',
                             placeholder: 'a case-insensitive regex' %>
    </div>

    <!-- Setters -->
    <div id='setters'>
      <%= render partial: 'fieldset',
                 collection: current_setters(rule),
                 as: :setter %>
    </div>

    <!-- New setter link -->
    <div class='row-fluid'>
      <div class='glyphicon-plus-action offset1'>
        <a class='new' href='#'>
          <i class='icon-plus'></i>new setter
        </a>
      </div>
    </div>

    <!-- Form errors -->
    <%= render 'shared/form_errors', model: rule %>

    <!-- Submit button -->
    <div class='row-fluid'>
      <%= f.submit class: 'btn btn-primary span12' %>
    </div>

    <!-- Cancel link -->
    <div class='row-fluid'>
      <%= link_to 'Cancel', @redirect_path, class: 'cancel' %>
    </div>
  <% end %>

  <!-- Hidden fieldset factory   -->
  <div id='fieldset-factory'>
    <%= render 'fieldset', setter: Rule.new %>
  </div>
</div>

app/views/rules/_preview.html.erb
<dl class='rule'>
  <dt>
    <span class='label label-info'><%= matcher.command %></span>
    <code><%= matcher.arg %></code> 
  </dt>
  <% matcher.setters.each do |setter| %>
    <dd>
      <span class='label label-success'><%= setter.command %></span>
      <code><%= setter.arg %></code> 
    </dd>
  <% end %>
</dl>

app/views/rules/_rule.html.erb
<div class='docs'>
  <div class='docs-header'>
    <h4><%= rule_heading(matcher) %></h4>
    <div class='actions'>
      <a class='edit'
         href='<%= edit_rule_path(matcher.id, redirect_path: @redirect_path) %>'>
        <i class='icon-edit'></i>edit</a>
      <a class='delete'
         href='<%= rule_path(matcher.id, redirect_path: @redirect_path) %>'
         data-method='delete' data-confirm='Are you sure?' rel='nofollow'>
         <i class='icon-trash'></i>delete</a>
    </div>
  </div>
  
  <dl class='rule'>
    <dt>
      <span class='label label-info hidden-phone'><%= matcher.command %></span>
      <span><i class='matcher-icon icon-filter visible-phone'></i></span>
      <code class='alert-info'><%= matcher_arg(matcher.arg) %></code> 
    </dt>
    <% matcher.setters.each do |setter| %>
      <dd>
        <span class='label label-success hidden-phone'><%= setter.command %></span>
        <span>
          <i class='setter-icon icon-<%= SETTER_ICONS[setter.command] %> visible-phone'></i>
        </span>
        <code class='alert-success'><%= setter_arg(setter.arg, matcher.arg) %></code> 
      </dd>
    <% end %>
  </dl>
</div>

app/views/rules/_rule_docs.html.erb
<div class='docs docs-rule'>
  <header>
    <h4><%= rule_heading(matcher) %></h4>
    <div class='glyphicon-plus-action'>
      <% if local_assigns[:show_bump] %>
        <a class='bump'
           href='<%= bump_rule_path(matcher.id, redirect_path: @redirect_path) %>'
           data-method='put' rel='nofollow'>
           <i class='icon-circle-arrow-up'></i>bump</a>
      <% end %>
      <a class='edit'
         href='<%= edit_rule_path(matcher.id, redirect_path: @redirect_path) %>'>
        <i class='icon-edit'></i>edit</a>
      <a class='delete'
         href='<%= rule_path(matcher.id, redirect_path: @redirect_path) %>'
         data-method='delete' data-confirm='Are you sure?' rel='nofollow'>
         <i class='icon-trash'></i>delete</a>
    </div>
  </header>

  <dl>
    <dt>
      <span class='label label-info hidden-phone'><%= matcher.command %></span>
      <span><i class='matcher-icon icon-filter visible-phone'></i></span>
      <code class='alert-info'><%= matcher_arg(matcher.arg) %></code>
    </dt>
    <% matcher.setters.each do |setter| %>
      <dd>
        <span class='label label-success hidden-phone'><%= setter.command %></span>
        <span><i class='setter-icon icon-<%= SETTER_ICONS[setter.command] %>
                        visible-phone'></i></span>
        <code class='alert-success'><%= setter_arg(setter.arg, matcher.arg) %></code>
      </dd>
    <% end %>
  </dl>
</div>

app/views/rules/_sidebar.html.erb
<div class='well sidebar-nav'>
  <ul class='nav nav-list'>
    <li class='nav-header'>Sort by</li>
    <li>
      <form action='<%= rules_path %>' method='get'>
        <% if params[:command].present? %>
          <%= hidden_field_tag :command, params[:command] %>
        <% end %>
        <%= select_tag 'sort-by',
                       options_for_select(sort_by_options, params['sort-by']) %>
      </form>
    </li>
    <li class='nav-header'>Filter by type</li>
    <% Activity::COMMANDS.each_with_index do |command, i| %>
      <li><%= link_to setter_name(command, i), setter_href(command) %></li>
    <% end %>
  </ul>
</div>

app/views/rules/edit.html.erb
<%= render 'form', rule: @rule %>

app/views/rules/index.html.erb
<% content_for :sidebar do %>
  <%= render 'sidebar' %>
<% end %>

<% if params[:command].present? %>
  <ul class='breadcrumb'>
    <li><%= link_to 'All', rules_path('sort-by' => params['sort-by']) %>
      <span class='divider'>/</span></li>
    <li class='active'><%= params[:command] %>
      <sup>(<%= @rules.count %>)</sup></li>
  </ul>
<% end %>

<% if @rules.present? %>
  <%= render partial: 'rule_docs', collection: @rules, as: :matcher %>
<% elsif params[:command].present? %>
  <h4>No match.</h4>
<% else %>
  <h4>No rule yet.</h4>
<% end %>

app/views/rules/new.html.erb
<%= render 'form', rule: @rule %>